[build]
builder = "nixpacks"
buildCommand = "npm run build"
startCommand = "npm run start"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"

[[services]]
name = "web"
[[services.ports]]
port = 3000
