[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 10
healthcheckRetries = 5

[[services]]
name = "web"
[[services.ports]]
port = 3000
httpGetHealthcheck = true
